//
// Created by elivelton on 9/29/20.
//

#include "error_handles.h"

char* getMessageFromID(int cod) {
    struct error_handle arr_erros[133] = {
            {1,   "Operation not permitted",                         "Operação não permitida",                                               "EPERM"},
            {2,   "No such file or directory",                       "Não existe esse arquivo ou diretório",                                 "ENOENT"},
            {3,   "No such process",                                 "Esse processo não existe",                                             "ESRCH"},
            {4,   "Interrupted system call",                         "Chamada de sistema interrompida",                                      "EINTR"},
            {5,   "I/O error",                                       "Erro de E / S",                                                        "EIO"},
            {6,   "No such device or address",                       "Não existe tal dispositivo ou endereço",                               "ENXIO"},
            {7,   "Argument list too long",                          "Lista de argumentos muito longa",                                      "E2BIG"},
            {8,   "Exec format error",                               "Erro de formato de execução",                                          "ENOEXEC"},
            {9,   "Bad file number",                                 "Número de arquivo inválido",                                           "EBADF"},
            {10,  "No child processes",                              "Nenhum processo filho",                                                "ECHILD"},
            {11,  "Try again",                                       "Tente novamente",                                                      "EAGAIN"},
            {12,  "Out of memory",                                   "Sem memória",                                                          "ENOMEM"},
            {13,  "Permission denied",                               "Permissão negada",                                                     "EACCES"},
            {14,  "Bad address",                                     "Endereço incorreto",                                                   "EFAULT"},
            {15,  "Block device required",                           "Dispositivo de bloqueio necessário",                                   "ENOTBLK"},
            {16,  "Device or resource busy",                         "Dispositivo ou recurso ocupado",                                       "EBUSY"},
            {17,  "File exists",                                     "Arquivo existe",                                                       "EEXIST"},
            {18,  "Cross-device link",                               "Link entre dispositivos",                                              "EXDEV"},
            {19,  "No such device",                                  "Dispositivo inexistente",                                              "ENODEV"},
            {20,  "Not a directory",                                 "Não é um diretório",                                                   "ENOTDIR"},
            {21,  "Is a directory",                                  "É um diretório",                                                       "EISDIR"},
            {22,  "Invalid argument",                                "Argumento inválido",                                                   "EINVAL"},
            {23,  "File table overflow",                             "Estouro de tabela de arquivo",                                         "ENFILE"},
            {24,  "Too many open files",                             "Muitos arquivos abertos",                                              "EMFILE"},
            {25,  "Not a typewriter",                                "Não é uma máquina de escrever",                                        "ENOTTY"},
            {26,  "Text file busy",                                  "Arquivo de texto ocupado",                                             "ETXTBSY"},
            {27,  "File too large",                                  "Arquivo muito grande",                                                 "EFBIG"},
            {28,  "No space left on device",                         "Sem espaço no dispositivo",                                            "ENOSPC"},
            {29,  "Illegal seek",                                    "Busca ilegal",                                                         "ESPIPE"},
            {30,  "Read-only file system",                           "Sistema de arquivos somente leitura",                                  "EROFS"},
            {31,  "Too many links",                                  "Muitos links",                                                         "EMLINK"},
            {32,  "Broken pipe",                                     "Tubo quebrado",                                                        "EPIPE"},
            {33,  "Math argument out of domain of func",             "Argumento matemático fora do domínio da função",                       "EDOM"},
            {34,  "Math result not representable",                   "Resultado matemático não representável",                               "ERANGE"},
            {35,  "Resource deadlock would occur",                   "Ocorreria impasse de recursos",                                        "EDEADLK"},
            {36,  "File name too long",                              "Nome de arquivo muito longo",                                          "ENAMETOOLONG"},
            {37,  "No record locks available",                       "Nenhum bloqueio de registro disponível",                               "ENOLCK"},
            {38,  "Invalid system call number",                      "Número da chamada de Sistema inválida",                                "ENOSYS"},
            {39,  "Directory not empty",                             "O diretório não está vazio",                                           "ENOTEMPTY"},
            {40,  "Too many symbolic links encountered",             "Vários links simbólicos encontrados",                                  "ELOOP"},
            {41,  "Operation would block",                           "A operação deveria ser bloqueada",                                     "EWOULDBLOCK EAGAIN"},
            {42,  "No message of desired type",                      "Nenhuma mensagem do tipo desejado",                                    "ENOMSG"},
            {43,  "Identifier removed",                              "Identificador removido",                                               "EIDRM"},
            {44,  "Channel number out of range",                     "Número do canal fora do alcance",                                      "ECHRNG"},
            {45,  "Level 2 not synchronized",                        "Nível 2 não sincronizado",                                             "EL2NSYNC"},
            {46,  "Level 3 halted",                                  "Nível 3 travado",                                                      "EL3HLT"},
            {47,  "Level 3 reset",                                   "Nível 3 redefinido",                                                   "EL3RST"},
            {48,  "Link number out of range",                        "Número do link fora do intervalo",                                     "ELNRNG"},
            {49,  "Protocol driver not attached",                    "Driver do protocolo não anexado",                                      "EUNATCH"},
            {50,  "No CSI structure available",                      "Estrutura CSI indisponível",                                           "ENOCSI"},
            {51,  "Level 2 halted",                                  "Nível 2 travado",                                                      "EL2HLT"},
            {52,  "Invalid exchange",                                "Troca inválida",                                                       "EBADE"},
            {53,  "Invalid request descriptor",                      "Descritor de solicitação inválido",                                    "EBADR"},
            {54,  "Exchange full",                                   "Troca cheia",                                                          "EXFULL"},
            {55,  "No anode",                                        "Sem �nodo",                                                            "ENOANO"},
            {56,  "Invalid request code",                            "Código de requisição inválido",                                        "EBADRQC"},
            {57,  "Invalid slot",                                    "Slot inválido",                                                        "EBADSLT"},
            {58,  "",                                                "",                                                                     "EDEADLOCK EDEADLK"},
            {59,  "Bad font file format",                            "Formato de arquivo incompatível",                                      "EBFONT"},
            {60,  "Device not a stream",                             "O dispositivo não é um stream",                                        "ENOSTR"},
            {61,  "No data available",                               "Nenhum dado disponível",                                               "ENODATA"},
            {62,  "Timer expired",                                   "O tempo expirou",                                                      "ETIME"},
            {63,  "Out of streams resources",                        "Recursos fora do stream",                                              "ENOSR"},
            {64,  "Machine is not on the network",                   "A máquina não está na rede",                                           "ENONET"},
            {65,  "Package not installed",                           "Pacote não instalado",                                                 "ENOPKG"},
            {66,  "Object is remote",                                "Objeto remoto",                                                        "EREMOTE"},
            {67,  "Link has been severed",                           "O link foi cortado",                                                   "ENOLINK"},
            {68,  "Advertise error",                                 "Erro de propaganda",                                                   "EADV"},
            {69,  "Srmount error",                                   "Erro de montagem",                                                     "ESRMNT"},
            {70,  "Communication error on send",                     "Erro ao enviar comunicação",                                           "ECOMM"},
            {71,  "Protocol error",                                  "Erro de protocolo",                                                    "EPROTO"},
            {72,  "Multihop attempted",                              "Tentativa de multihop",                                                "EMULTIHOP"},
            {73,  "RFS specific error",                              "Erro específico de RFS",                                               "EDOTDOT"},
            {74,  "Not a data message",                              "Não é uma mensagem de dados",                                          "EBADMSG"},
            {75,  "Value too large for defined data type",           "O valor é muito grande para o tipo de dado definido",                  "EOVERFLOW"},
            {76,  "Name not unique on network",                      "O nome não é exclusivo na rede",                                       "ENOTUNIQ"},
            {77,  "File descriptor in bad state",                    "Descritor de arquivos incompatível",                                   "EBADFD"},
            {78,  "Remote address changed",                          "Endereço remoto alterado",                                             "EREMCHG"},
            {79,  "Can not access a needed shared library",          "Não foi possível acessar uma biblioteca necessária compartilhada",     "ELIBACC"},
            {80,  "Accessing a corrupted shared library",            "O acesso a uma biblioteca compartilhada está corrompido",              "ELIBBAD"},
            {81,  ".lib section in a.out corrupted",                 "A biblioteca da sessão a.out está corrompida",                         "ELIBSCN"},
            {82,  "Attempting to link in too many shared libraries", "Tentativa de vincular em diferentes bibliotecas compartilhadas",       "ELIBMAX"},
            {83,  "Cannot exec a shared library directly",           "Não é possível executar uma biblioteca compartilhada diretamente",     "ELIBEXEC"},
            {84,  "Illegal byte sequence",                           "Sequência de bytes inválidos",                                         "EILSEQ"},
            {85,  "Interrupted system call should be restarted",     "A interrupção da chamada de Sistema deve ser reiniciada",              "ERESTART"},
            {86,  "Streams pipe error",                              "Erro no canal de streams",                                             "ESTRPIPE"},
            {87,  "Too many users",                                  "Muitos usuários",                                                      "EUSERS"},
            {88,  "Socket operation on non-socket",                  "Operação de soquetes em não soquetes",                                 "ENOTSOCK"},
            {89,  "Destination address required",                    "O Endereço de destino é obrigatório",                                  "EDESTADDRREQ"},
            {90,  "Message too long",                                "Mensagem muito longa",                                                 "EMSGSIZE"},
            {91,  "Protocol wrong type for socket",                  "Tipo de protocolo inválido para o soquete",                            "EPROTOTYPE"},
            {92,  "Protocol not available",                          "Protocolo não disponível",                                             "ENOPROTOOPT"},
            {93,  "Protocol not supported",                          "Protocolo não compatável",                                             "EPROTONOSUPPORT"},
            {94,  "Socket type not supported",                       "O tipo de soquete não é compatível",                                   "ESOCKTNOSUPPORT"},
            {95,  "Operation not supported on transport endpoint",   "Operação não suportada pelo terminal de transporte",                   "EOPNOTSUPP"},
            {96,  "Protocol family not supported",                   "Família de protocolo não compatível",                                  "EPFNOSUPPORT"},
            {97,  "Address family not supported by protocol",        "Família de endereços não suportada pelo protocolo",                    "EAFNOSUPPORT"},
            {98,  "Address already in use",                          "O endereço já está em uso",                                            "EADDRINUSE"},
            {99,  "Cannot assign requested address",                 "Não é possível identificar o endereço indicado",                       "EADDRNOTAVAIL"},
            {100, "Network is down",                                 "A rede está fora do ar",                                               "ENETDOWN"},
            {101, "Network is unreachable",                          "A rede está inacessável",                                              "ENETUNREACH"},
            {102, "Network dropped connection because of reset",     "A conexão da rede caiu devido � redefinição",                          "ENETRESET"},
            {103, "Software caused connection abort",                "Um Software causou interrupção da conexão",                            "ECONNABORTED"},
            {104, "Connection reset by peer",                        "Conexão redefinida por par",                                           "ECONNRESET"},
            {105, "No buffer space available",                       "Nenhum espaço de buffer disponível",                                   "ENOBUFS"},
            {106, "Transport endpoint is already connected",         "O Endpoint de transporte já está conectado",                           "EISCONN"},
            {107, "Transport endpoint is not connected",             "O Endpoint de transporte não está conectado",                          "ENOTCONN"},
            {108, "Cannot send after transport endpoint shutdown",   "Não é possível enviar após o desligamento do endpoint de  transporte", "ESHUTDOWN"},
            {109, "Too many references: cannot splice",              "Muitas referências: não é possível unir",                              "ETOOMANYREFS"},
            {110, "Connection timed out",                            "A conexão expirou",                                                    "ETIMEDOUT"},
            {111, "Connection refused",                              "Conexão recusada",                                                     "ECONNREFUSED"},
            {112, "Host is down",                                    "O host está fora do ar",                                               "EHOSTDOWN"},
            {113, "No route to host",                                "Nenhuma rota para o host",                                             "EHOSTUNREACH"},
            {114, "Operation already in progress",                   "A operação já está em andamento",                                      "EALREADY"},
            {115, "Operation now in progress",                       "Operação em andamento agora",                                          "EINPROGRESS"},
            {116, "Stale file handle",                               "Identificador de arquivo obsoleto",                                    "ESTALE"},
            {117, "Structure needs cleaning",                        "A estrutura precisa de limpeza",                                       "EUCLEAN"},
            {118, "Not a XENIX named type file",                     "XENIX não é um arquivo de tipo nomeado",                               "ENOTNAM"},
            {119, "No XENIX semaphores available",                   "Sem semáforos XENIX disponíveis",                                      "ENAVAIL"},
            {120, "Is a named type file",                            "É um arquivo de tipo nomeado",                                         "EISNAM"},
            {121, "Remote I/O error",                                "Erro de entrada e saída remota",                                       "EREMOTEIO"},
            {122, "Quota exceeded",                                  "Cota excedida",                                                        "EDQUOT"},
            {123, "No medium found",                                 "Nenhuma mídia encontrada",                                             "ENOMEDIUM"},
            {124, "Wrong medium type",                               "Tipo de meio errado",                                                  "EMEDIUMTYPE"},
            {125, "Operation Canceled",                              "Operação cancelada",                                                   "ECANCELED"},
            {126, "Required key not available",                      "A Chave requirida não está disponível",                                "ENOKEY"},
            {127, "Key has expired",                                 "A chave expirou",                                                      "EKEYEXPIRED"},
            {128, "Key has been revoked",                            "A chave foi revogada",                                                 "EKEYREVOKED"},
            {129, "Key was rejected by service",                     "A chave foi rejeitada pelo serviço",                                   "EKEYREJECTED"},
            {130, "Owner died",                                      "O proprietário morreu",                                                "EOWNERDEAD"},
            {131, "State not recoverable",                           "Estado não recuperável",                                               "ENOTRECOVERABLE"},
            {132, "Operation not possible due to RF-kill",           "Operação não disponível devido ao RF-kill",                            "ERFKILL"},
            {133, "Memory page has hardware error",                  "Erro de hardware na página de memória",                                "EHWPOISON"},

    };
    return arr_erros[cod - 1].translated_message;
}
